base_config:
  - ./diffsr_base.yaml
  - ./df2k4x.yaml
trainer_cls: tasks.srdiff_sat.SRDiffSat

# model
unet_dim_mults: 1|2|3|4
decay_steps: 100000
hidden_size: 64
rrdb_num_feat: 32
rrdb_num_block: 8


# train and test
batch_size: 64
max_updates: 400000
eval_batch_size: 64
test_batch_size: 1
train_diffsr: true
val_check_interval: 75000
save_ckpt_interval : 25000
train_diffsr: true
sen2_amount: 8
use_ltae: false
use_rrdb: false
use_highresnet: false
use_rrdb_ltae: true
misr_ref_image: closest
misr: true
sr_scale: 4
