base_config:
  - ./diffsr_base.yaml
  - ./df2k4x.yaml
trainer_cls: tasks.srdiff_sat.SRDiffSat

# model
unet_dim_mults: 1|2|3|4
decay_steps: 200000

# train and test
batch_size: 32
max_updates: 10
eval_batch_size: 16
test_batch_size: 1
train_diffsr: true
val_check_interval: 2
save_ckpt_interval : 2500
train_diffsr: true
sen2_amount: 8

