base_config:
  - ./diffsr_base.yaml
  - ./df2k4x.yaml
trainer_cls: tasks.srdiff_sat.SRDiffSat

lr: 0.0002
# model
unet_dim_mults: 1|2|3|4
decay_steps: 50000

# train and test
batch_size: 32
max_updates: 50000
eval_batch_size: 32
test_batch_size: 1
train_diffsr: true
val_check_interval: 25000
save_ckpt_interval : 10
use_rrdb: false
rrdb_num_feat: 1
sen2_amount: 1
fix_rrdb: true
