base_config:
  - ../sr_base.yaml
  - ../df2k4x.yaml
trainer_cls: tasks.rrdb.RRDBSatTask
# model
hidden_size: 32
lr: 0.0008
num_block: 15

# train and eval
max_updates: 100
batch_size: 64
eval_batch_size: 1
valid_steps: 3
save_ckpt_interval: 1000
val_check_interval: 50000
subset_test: true
loss_type: l1
sen2_amount: 1
