base_config:
  - ../sr_base.yaml
  - ../df2k4x.yaml
trainer_cls: tasks.rrdb.RRDBSatTask
# model
hidden_size: 32
lr: 0.0002
num_block: 15

# train and eval
max_updates: 400000
batch_size: 32
eval_batch_size: 32
valid_steps: 3
train_diffsr: false
save_ckpt_interval: 20000
val_check_interval: 25000
sen2_amount: 1
train_diffsr: false
loss_type: l1_shift
