base_config:
  - ../sr_base.yaml
  - ../df2k4x.yaml
trainer_cls: tasks.highresnet.HighResnet
# model
hidden_size: 32
lr: 0.0006
num_block: 15

# train and eval
max_updates: 400000
batch_size: 32
eval_batch_size: 64
test_batch_size: 1
val_check_interval: 50000
save_ckpt_interval : 50000
sen2_amount: 8
train_diffsr: false
# add these lines for testing:
save_intermediate: False
test_save_png: False
misr: True
test_diff: False
