base_config:
  - ../sr_base.yaml
  - ../df2k4x.yaml
trainer_cls: tasks.highresnet.HighResnet

lr: 0.0007

# train and eval
max_updates: 50000
batch_size: 64
eval_batch_size: 64
test_batch_size: 1
val_check_interval: 10
save_ckpt_interval : 100
sen2_amount: 8
subset_test: true
