# config file for HighRes-net L-TAE

base_config:
  - ../sr_base.yaml
  - ../df2k4x.yaml
trainer_cls: tasks.hr_ltae.MISR
# model
hidden_size: 64
lr: 0.0007
num_block: 17

# train and eval
max_updates: 400000
batch_size: 32
eval_batch_size: 32
test_batch_size: 1
val_check_interval: 50000
save_ckpt_interval : 40000
train_diffsr: false
sen2_amount: 8
misr_ref_image: closest # closest or median -> reference image (for more details please refer to HighRes-net paper)
# add these lines for testing:
save_intermediate: False
test_save_png: False
misr: True
test_diff: False
