base_config:
  - ../sr_base.yaml
  - ../df2k4x.yaml
trainer_cls: tasks.rrdb_highresnet_fusion.RRDBhighresnet
# model
hidden_size: 32
lr: 0.0002
num_block: 15

# train and eval
max_updates: 400000
batch_size: 16
eval_batch_size: 16
test_batch_size: 1
val_check_interval: 25000
save_ckpt_interval : 25000
train_diffsr: false
sen2_amount: 8
train_diffsr: false
